BibliotecaTech/Models/AutorModel.cs
using System.ComponentModel.DataAnnotations;

namespace BibliotecaTech.Models
{
    public class AutorModel
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Informe o nome do autor!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe a data de nascimento do autor!")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime DataNascimento { get; set; }
    }
}

BibliotecaTech/Models/EditoraModel.cs
using System.ComponentModel.DataAnnotations;

namespace BibliotecaTech.Models
{
    public class EditoraModel
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome da editora!")]
        public string Nome { get; set; }
    }
}

BibliotecaTech/Models/ErrorViewModel.cs
namespace BibliotecaTech.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BibliotecaTech/Models/LivroModel.cs
namespace BibliotecaTech.Models
{
    public class LivroModel
    {
        
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataPublicacao { get; set; }
        public string Isbn { get; set; }
        public int EditoraId { get; set; }
        public int AutorId { get; set; }

        // Propriedades de navegação
        public virtual AutorModel Autor { get; set; }
        public virtual EditoraModel Editora { get; set; }
    }
}

BibliotecaTech/Controllers/AutorController.cs
using BibliotecaTech.Data;
using BibliotecaTech.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace BibliotecaTech.Controllers
{
    public class AutorController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AutorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<AutorModel> autores = _context.Autores;
            return View(autores);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AutorModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Autores.Add(model);
                _context.SaveChanges();
                TempData["MensagemSucesso"] = "Autor cadastrado com sucesso!";
                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Ocorreu um erro ao cadastrar o autor!";
            return View();
        }

        [HttpGet]
        public IActionResult Update(int? id) 
        {
            if (id == null || id == 0) 
            {
                return NotFound();
            }
            AutorModel autor = _context.Autores.FirstOrDefault(x => x.Id == id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        [HttpPost]
        public IActionResult Update(AutorModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Autores.Update(model);
                _context.SaveChanges();
                TempData["MensagemSucesso"] = "Autor atualizado com sucesso!";
                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Ocorreu um erro ao atualizar o autor!";

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            AutorModel autor = _context.Autores.FirstOrDefault(x => x.Id==id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        [HttpPost]
        public IActionResult Delete(AutorModel model)
        {
            if (model == null)
            {
                return NotFound();
            }
            _context.Autores.Remove(model);
            _context.SaveChanges();
            TempData["MensagemSucesso"] = "Deleção realizada com sucesso!";
            return RedirectToAction("Index");
        }
    }
}

BibliotecaTech/Controllers/EditoraController.cs
using BibliotecaTech.Data;
using BibliotecaTech.Models;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaTech.Controllers
{
    public class EditoraController : Controller
    {
        private readonly ApplicationDbContext _context;
        public EditoraController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<EditoraModel> editoras = _context.Editoras;
            return View(editoras);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EditoraModel editora)
        {
            if (ModelState.IsValid)
            {
                _context.Editoras.Add(editora);
                _context.SaveChanges();
                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";
                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Ocorreu um erro ao realizar o cadastro!";

            return View();
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            EditoraModel editora = _context.Editoras.FirstOrDefault(x => x.Id == id);
            if (editora == null)
            {
                return NotFound();
            }
            return View(editora);
        }

        [HttpPost]
        public IActionResult Update(EditoraModel editora)
        {
            if (ModelState.IsValid)
            {
                _context.Editoras.Update(editora);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizada com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Ocorreu um erro ao realizar a edição!";

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EditoraModel editora = _context.Editoras.FirstOrDefault(x => x.Id == id);
            if (editora == null)
            {
                return NotFound();
            }
            return View(editora);
        }

        [HttpPost]
        public IActionResult Delete(EditoraModel editora)
        {
            if (editora == null)
            {
                return NotFound();

            }
            _context.Editoras.Remove(editora);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Deleção realizada com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

BibliotecaTech/Controllers/HomeController.cs
using BibliotecaTech.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BibliotecaTech.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BibliotecaTech/Views/Autor/Create.cshtml
@model AutorModel;

@{
    ViewData["title"] = "Cadastrar um autor";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de autores</h1>
    </div>
    <form method="post" asp-controller="Autor" asp-action="Create">
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do autor:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome do autor?">
            <span asp-validation-for="Nome" class="text-danger"></span>

            <label for="DataNascimento" class="form-label text-light pt-3">Data de nascimento do autor:</label>
            <input type="date" class="form-control text-light" asp-for="DataNascimento" id="DataNascimento">
            <span asp-validation-for="DataNascimento" class="text-danger"></span>

        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
            <a class="btn btn-primary w-50" asp-controller="Autor" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Autor/Delete.cshtml
@model AutorModel
@{
    ViewData["title"] = "Deleção de autor";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Deleção de autores</h1>
    </div>
    <form method="post" asp-controller="Autor" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <h2 class="text-warning text-center">Tem certeza que deseja excluir o registro abaixo ?</h2>
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do autor:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome do autor?">
            <span asp-validation-for="Nome" class="text-danger"></span>

            <label for="DataNascimento" class="form-label text-light pt-3">Data de nascimento do autor:</label>
            <input type="date" class="form-control text-light" asp-for="DataNascimento" id="DataNascimento">
            <span asp-validation-for="DataNascimento" class="text-danger"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Autor" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Autor/Index.cshtml
@model IEnumerable<AutorModel>

@{
    ViewData["title"] = "Lista de autores";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Autores</h1>
        <a class="btn btn-success mx-2" asp-controller="Autor" asp-action="Create"><i class="bi bi-plus-square mx-2"></i>Cadastrar novo autor</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <div class="table-responsive">
        <table id="tabela-formatada" class="table table-sm table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome do Autor</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>

                @if (Model != null)
                {
                    @foreach (var autor in Model)
                    {
                        <tr>
                            <td>@autor.Id</td>
                            <td>@autor.Nome</td>
                            <td>@Html.DisplayFor(model => autor.DataNascimento)</td>
                            <td>
                                <a class="btn btn-warning mx-2" asp-controller="Autor" asp-route-id="@autor.Id" asp-action="Update"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            </td>
                            <td>
                                <a class="btn btn-danger mx-2" asp-controller="Autor" asp-route-id="@autor.Id" asp-action="Delete"><i class="bi bi-trash3-fill mx-2"></i>Excluir</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

BibliotecaTech/Views/Autor/Update.cshtml
@model AutorModel;

@{
    ViewData["title"] = "Edição de um autor";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de autores</h1>
    </div>
    <form method="post" asp-controller="Autor" asp-action="Update">
        <input type="hidden" asp-for="Id" />
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome do autor:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome do autor?">
            <span asp-validation-for="Nome" class="text-danger"></span>

            <label for="DataNascimento" class="form-label text-light pt-3">Data de nascimento do autor:</label>
            <input type="date" class="form-control text-light" asp-for="DataNascimento" id="DataNascimento">
            <span asp-validation-for="DataNascimento" class="text-danger"></span>

        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Autor" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Editora/Create.cshtml
@model EditoraModel
@{
    ViewData["title"] = "Cadastrar Editora";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de editoras</h1>
    </div>
    <form method="post" asp-controller="Editora" asp-action="Create">
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome da editora:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome da editora?">  
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
      
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
            <a class="btn btn-primary w-50" asp-controller="Editora" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Editora/Delete.cshtml
@model EditoraModel
@{
    ViewData["title"] = "Deleção de editora";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Deleção de editoras</h1>
    </div>
    <form method="post" asp-controller="Editora" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <h2 class="text-warning text-center">Tem certeza que deseja excluir o registro abaixo ?</h2>
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome da editora:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome da editora?" disabled>
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Editora" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Editora/Index.cshtml
@model IEnumerable<EditoraModel> // Aqui eu pego o esqueleto (meu modelo para a view)]

@{
    ViewData["title"] = "Lista de editoras";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Editoras</h1>
        <a class="btn btn-success mx-2" asp-controller="Editora" asp-action="Create"><i class="bi bi-plus-square mx-2"></i>Cadastrar nova editora</a>
    </div>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert"> 
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <div class="table-responsive">
    <table id="tabela-formatada" class="table table-sm table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome da Editora</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        
            @if(Model != null)
            {
                @foreach(var editora in Model)
                {
                    <tr>
                        <td>@editora.Id</td>
                        <td>@editora.Nome</td>
                        <td>
                                <a class="btn btn-warning mx-2" asp-controller="Editora" asp-route-id="@editora.Id" asp-action="Update"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                        </td>
                        <td>
                                <a class="btn btn-danger mx-2" asp-controller="Editora" asp-route-id="@editora.Id" asp-action="Delete"><i class="bi bi-trash3-fill mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    </div>
</div>

BibliotecaTech/Views/Editora/Update.cshtml
@model EditoraModel
@{
    ViewData["title"] = "Edição de editora";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de editoras</h1>
    </div>
    <form method="post" asp-controller="Editora" asp-action="Update">
        <input type="hidden" asp-for="Id" />
        <div class="mb-3">
            <label for="Nome" class="form-label text-light">Nome da editora:</label>
            <input type="text" class="form-control text-light" asp-for="Nome" id="Nome" placeholder="Qual o nome da editora?">
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-warning w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Editora" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

BibliotecaTech/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Biblioteca Tech - Sistema de Biblioteca Online</h1>
    <div>
        <img src="/img/logo.png" />
    </div>
</div>

BibliotecaTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BibliotecaTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BibliotecaTech.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.0/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">BibliotecaTech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-shield-fill-exclamation mx-2"></i>Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Editora" asp-action="Index"><i class="bi bi-bookmarks-fill mx-2"></i>Editoras</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Autor" asp-action="Index"><i class="bi bi-person-vcard mx-2"></i>Autores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - BibliotecaTech - Desenvolvido por Tiago Euzébio Cordeiro | <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.0/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>